package domain

import (
	"context"
	"time"
)

// ClickEvent represents a single redirect event, processed asynchronously.
// It is created during redirect and enqueued to QStash — the worker
// persists it to PostgreSQL without blocking the redirect response.
type ClickEvent struct {
	ID          string // UUID — generated by worker before insert
	LinkID      int64
	ABTestID    string // empty string means no A/B test was involved
	IPAddress   string // masked at application layer: "x.x.0.0" format
	CountryCode string // ISO 3166-1 alpha-2, resolved via ip-api.com
	City        string
	Device      string // "desktop" | "mobile" | "tablet" | "bot"
	OS          string // e.g. "Windows", "macOS", "Android", "iOS"
	Browser     string // e.g. "Chrome", "Safari", "Firefox"
	Referrer    string // domain only, no path or query params
	UserAgent   string // full user agent string
	ClickedAt   time.Time
}

// ClickEventPayload is the JSON structure published to QStash.
// Kept flat and minimal to reduce serialization overhead on the hot path.
type ClickEventPayload struct {
	LinkID    int64  `json:"link_id"`
	ABTestID  string `json:"ab_test_id,omitempty"`
	IPAddress string `json:"ip_address"` // raw IP — masking happens in worker
	UserAgent string `json:"user_agent"`
	Referrer  string `json:"referrer"`   // raw referrer — stripping happens in worker
	ClickedAt string `json:"clicked_at"` // RFC3339
}

// --- Analytics query result types ---

// AnalyticsSummary is the top-level analytics overview for a link.
type AnalyticsSummary struct {
	LinkID      int64   `json:"link_id"`
	TotalClicks int64   `json:"total_clicks"`
	UniqueIPs   int64   `json:"unique_ips"` // approximation based on masked IPs
	CTR         float64 `json:"ctr"`        // reserved for future use
}

// TimeSeriesPoint represents click count for a single time bucket.
type TimeSeriesPoint struct {
	Bucket time.Time `json:"bucket"`
	Clicks int64     `json:"clicks"`
}

// BreakdownItem represents a single row in a breakdown (country, device, etc).
type BreakdownItem struct {
	Label      string  `json:"label"` // e.g. "ID", "desktop", "Chrome"
	Clicks     int64   `json:"clicks"`
	Percentage float64 `json:"percentage"`
}

// AnalyticsBreakdown holds all breakdown dimensions for a link.
type AnalyticsBreakdown struct {
	Countries []BreakdownItem `json:"countries"`
	Devices   []BreakdownItem `json:"devices"`
	OSes      []BreakdownItem `json:"oses"`
	Browsers  []BreakdownItem `json:"browsers"`
	Referrers []BreakdownItem `json:"referrers"`
}

// AnalyticsFilter defines query parameters for analytics endpoints.
type AnalyticsFilter struct {
	LinkID      int64
	StartDate   time.Time
	EndDate     time.Time
	Granularity string // "hour" | "day"
	Limit       int
}

// --- Repository interface ---

// AnalyticsRepository defines persistence for click events and analytics queries.
type AnalyticsRepository interface {
	// SaveClickEvent persists a processed ClickEvent to the database.
	SaveClickEvent(ctx context.Context, event *ClickEvent) error

	// GetSummary returns aggregate stats for a link.
	GetSummary(ctx context.Context, filter AnalyticsFilter) (*AnalyticsSummary, error)

	// GetTimeSeries returns click counts bucketed by hour or day.
	GetTimeSeries(ctx context.Context, filter AnalyticsFilter) ([]TimeSeriesPoint, error)

	// GetBreakdown returns breakdown by country, device, OS, browser, referrer.
	GetBreakdown(ctx context.Context, filter AnalyticsFilter) (*AnalyticsBreakdown, error)

	// GetRecentClicks returns the most recent N click events for a link.
	GetRecentClicks(ctx context.Context, linkID int64, limit int) ([]*ClickEvent, error)
}

// --- Usecase interface ---

// AnalyticsUsecase defines business logic for analytics queries.
type AnalyticsUsecase interface {
	// GetSummary returns top-level stats for a link owned by userID.
	GetSummary(ctx context.Context, linkID int64, userID string, filter AnalyticsFilter) (*AnalyticsSummary, error)

	// GetTimeSeries returns time-bucketed click counts.
	GetTimeSeries(ctx context.Context, linkID int64, userID string, filter AnalyticsFilter) ([]TimeSeriesPoint, error)

	// GetBreakdown returns all dimension breakdowns.
	GetBreakdown(ctx context.Context, linkID int64, userID string, filter AnalyticsFilter) (*AnalyticsBreakdown, error)

	// GetRecentClicks returns the latest click events.
	GetRecentClicks(ctx context.Context, linkID int64, userID string, limit int) ([]*ClickEvent, error)

	// ProcessClickEvent is called by the worker to persist an inbound event.
	ProcessClickEvent(ctx context.Context, payload ClickEventPayload) error
}
